### ISSUE TITLE
not working with native aot: Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by ivanjx** [MartinKuschnik/WmiLight#12]
my code:
```cs
        string query = string.Format(
            "SELECT * from Win32_Printer WHERE Name = '{0}'",
            printerName);
        using WmiConnection con = new WmiConnection();
        ushort status = (ushort)PrinterStatus.Unknown;

        foreach (WmiObject process in con.CreateQuery(query))
        {
            status = (ushort)process["PrinterStatus"];
        }

        return (PrinterStatus)status;
```

the error:
```
Common Language Runtime detected an invalid program. The body of method 'Void WmiLight.Wbem.WbemLocator..ctor()' is invalid.
System.InvalidProgramException: Common Language Runtime detected an invalid program. The body of method 'Void WmiLight.Wbem.WbemLocator..ctor()' is invalid.
   at Internal.Runtime.TypeLoaderExceptionHelper.CreateInvalidProgramException(ExceptionStringID, String) + 0x40
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowInvalidProgramExceptionWithArgument(ExceptionStringID, String) + 0x9
   at WmiLight.Wbem.WbemLocator..ctor() + 0x15
   at WmiLight.WmiConnection.Open() + 0x43
   at WmiLight.WmiConnection.InternalExecuteQuery(WmiQuery query) + 0x39
   at WmiLight.WmiConnection.ExecuteQuery(WmiQuery query) + 0x2c
```

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="myassemblyname" />
    <TrimmerRootAssembly Include="WmiLight" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.EventLog" Version="3.1.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
    <PackageReference Include="WmiLight" Version="4.0.0" />
  </ItemGroup>

</Project>
```

**Comment by MartinKuschnik** [comment]
AOT is currently not supported. Lease see #11 for more details.

**Comment by MartinKuschnik** [comment]
I'm working on a new verion that is compatible with AOT. It will take a few days.

**Comment by ivanjx** [comment]
thanks a lot @MartinKuschnik the latest pre release version works perfectly in my case!

**Comment by ivanjx** [comment]
one more thing is it possible to compile the cpp wrapper as a static library so it wont output a dll similar to this https://github.com/AvaloniaUI/Avalonia/issues/9503

**Comment by MartinKuschnik** [comment]
"Static library" means that the library is going to be merged with your final application. This concept doesn't exist in .net. .net supports DLLs only. 

Maybe there's a way by using C++ CLI but this would require more work - sorry.

**Comment by ivanjx** [comment]
the concept does not exists with .net but it does exist with .NET Native AOT

**Comment by ivanjx** [comment]
easier deployment. also to make sure the dependency will always be there and cannot be easily altered.

**Comment by MartinKuschnik** [comment]
I can add the static lib but does not know how to link it in the project file without using absolute paths.

**Comment by ivanjx** [comment]
im fine with just be able to compile it myself like i did with skiasharp

**Comment by MartinKuschnik** [comment]
try version 5.0.1-pre

![image](https://github.com/MartinKuschnik/WmiLight/assets/2582960/e3d07bec-f98b-4f62-a31c-6a78b501ec49)

**Comment by ivanjx** [comment]
thanks a lot. i will try it in a few hours.

**Comment by MartinKuschnik** [comment]
For me worked:

```xml
<ItemGroup>
  <!-- Generate direct PInvokes for Dependency -->
  <DirectPInvoke Include="WmiLight.Native.dll" />
  <!-- Specify library to link against -->
  <NativeLibrary Include="wbemuuid.lib" Condition="$(RuntimeIdentifier.StartsWith('win'))" />
  <NativeLibrary Include="path to x64 WmiLight.Native.lib " Condition="$(RuntimeIdentifier.StartsWith('win'))" />
</ItemGroup>
```

**Comment by MartinKuschnik** [comment]
Please try `v.5.0.1-pre2`...

![image](https://github.com/MartinKuschnik/WmiLight/assets/2582960/f7bb8534-8225-41af-a870-966d939430c5)

**Comment by MartinKuschnik** [comment]
@ivanjx Works for you?

**Comment by ivanjx** [comment]
hi @MartinKuschnik 

sorry i was tasked with different projects. i have tried your new nuget but it does not seem to copy the lib files into the directory. i grabbed the .lib files manually and it seemed to work but i am still missing the `wbemuuid.lib`. where can i find this? thanks.

**Comment by ivanjx** [comment]
@MartinKuschnik thanks! now the warnings are gone. though i still not able to use this `$(OutputPath)WmiLight.Native.lib` but it is fine as long as i can use the .lib file.

**Comment by ivanjx** [comment]
it is okay not to include the .lib at all as long as there is an easy way to compile it myself or just download it.

**Comment by MartinKuschnik** [comment]
@ivanjx Please have a look to [Version 5.1.1](https://github.com/MartinKuschnik/WmiLight/releases/tag/v5.1.1) and [Native AOT deployment](https://github.com/MartinKuschnik/WmiLight/blob/master/README.md#native-aot-deployment).

You should be able to replace

```xml
  <!-- Generate direct PInvokes for Dependency -->
  <DirectPInvoke Include="WmiLight.Native.dll" />
  <!-- Specify library to link against -->
  <NativeLibrary Include="wbemuuid.lib" Condition="$(RuntimeIdentifier.StartsWith('win'))" />
  <NativeLibrary Include="path to x64 WmiLight.Native.lib " Condition="$(RuntimeIdentifier.StartsWith('win'))" />
```

with 

```xml
    <PublishWmiLightStaticallyLinked>true</PublishWmiLightStaticallyLinked>
```

**Comment by ivanjx** [comment]
@MartinKuschnik just tried and it works well. thanks.
