### ISSUE TITLE
NativeAOT publish fails to statically link WmiLight when it is packaged in a dependent library

### ISSUE THREAD

**Issue by danielo-unity3d** [MartinKuschnik/WmiLight#14]
... rather than when used directly in the main program.

Note: I am using dotnet 8.0.202

Actually, the only reason I was eventually able to get a simple WmiLight program to work, was by setting `PublishWmiLightStaticallyLinked` to true in the main project.

Unfortunately, I don't seem to be able to get this to work when the WMI code is in a dependent library (setting the attribute either in the main project or library project has no discernable impact).

## Steps:
`dotnet new globaljson --sdk-version 8.0.202 --force`
`dotnet new console -n Main`
`dotnet new classlib -n Lib`
`dotnet add Main reference Lib`
`dotnet add Lib package WmiLight`

We set `IsAotCompatible` (or just `IsTrimmable`) in both `Main` and `Lib`, but we set `PublishAot` in the `Main` project alone (I don't think the latter have any effect if set in the library).
Sadly, setting `PublishWmiLightStaticallyLinked` in either the `Main`, the `Lib`, or both, has no effect.

The code in `Lib/ClassLib.cs`:
```C#
using WmiLight;

namespace Lib;

public class Class1
{
    public static void GetNetworkAddresses()
    {
        using (WmiConnection con = new WmiConnection("root\\StandardCimv2"))
        {
            foreach (WmiObject managementObject in con.CreateQuery("SELECT PermanentAddress FROM MSFT_NetAdapter"))
            {
                var permanentAddress = managementObject["PermanentAddress"] as string;
                if (!string.IsNullOrEmpty(permanentAddress))
                {
                    Console.WriteLine($"  {permanentAddress.ToLower()}");
                }
            }
        }
    }
}
```

The code in `Main/Program.cs`:
```C#
Lib.Class1.GetNetworkAddresses();
```

The command to `publish`:
```
$ dotnet publish Main
```
and to run:
```
$ Main/bin/Release/net8.0/win-x64/publish/Main.exe 
  14cc19d330a0
  025049000021
  18dc18e3301c
```

But the `WmiLight.Native.dll` is never substituted for the static library.
```
$ ll Main/bin/Release/net8.0/win-x64/publish/
total 10656
-rw-r--r-- 1 danielo 197121   11448 Mar 13 09:13 Lib.pdb
-rwxr-xr-x 1 danielo 197121 1860608 Mar 13 09:13 Main.exe*
-rw-r--r-- 1 danielo 197121 8925184 Mar 13 09:13 Main.pdb
-rwxr-xr-x 1 danielo 197121  109056 Dec 11 05:16 WmiLight.Native.dll*
```
Thanks for your help.

**Comment by MartinKuschnik** [comment]
Hi @danielo-unity3d,

this does not work, because the `PublishWmiLightStaticallyLinked` option that is introduced by the NuGet package and configures the linker. But this works only on an application not an a library. And because you do not have installed the NuGet package at the main project, ther are no linker properties generated.

It hink you have the following options:
- install the NuGet package also to the main project
- configure the linker properties by your own (see [WmiLight.props](https://github.com/MartinKuschnik/WmiLight/blob/master/WmiLight/.nuget/.build/WmiLight.props) and [WmiLight.targets](https://github.com/MartinKuschnik/WmiLight/blob/master/WmiLight/.nuget/.build/WmiLight.targets))

**Comment by MartinKuschnik** [comment]
@danielo-unity3d Do you still need help?

**Comment by danielo-unity3d** [comment]
If the application is trimmed (`PublishTrimmed` is true), then I get this exception:
```
Exception has occurred: CLR/System.TypeLoadException
Exception thrown: 'System.TypeLoadException' in WmiLight.dll: 'Could not load type 'System.StubHelpers.ObjectMarshaler' from assembly 'System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.'
```

**Comment by MartinKuschnik** [comment]
It works in my case. I do not get any exception.

Can you please check my test project and tell me the difference?

[test-project.zip](https://github.com/MartinKuschnik/WmiLight/files/14628509/test-project.zip)

**Comment by MartinKuschnik** [comment]
oh, you mean without NativeAOT?

**Comment by MartinKuschnik** [comment]
We will follow this bug at #15

**Comment by MartinKuschnik** [comment]
@danielo-unity3d Please try to enable the `BuiltInComInteropSupport` feature. See [Trimming during publish](https://github.com/MartinKuschnik/WmiLight?tab=readme-ov-file#trimming-during-publish) for mor details.

Please give me some feedback.

**Comment by danielo-unity3d** [comment]
Just adding `BuiltInComInteropSupport` to true, I get:
```
$ dotnet publish -p:PublishBuildType=Trimmed
...
Optimizing assemblies for size. This process might take a while.
ILLink : Trim analysis error IL2026: Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeInternal(ComActivationContextInternal*)
: Using member 'Internal.Runtime.InteropServices.ComActivator.GetClassFactoryForTypeImpl(ComActivationContextInternal*, Boolean)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Built-in COM support is not trim compatible. https://aka.ms/dotnet-illink/com
C:\Users\user\.nuget\packages\microsoft.net.illink.tasks\8.0.3\build\Microsoft.NET.ILLink.targets(87,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
```

**Comment by MartinKuschnik** [comment]
@danielo-unity3d I think i have found a way to fully remove the COM stuff. But I have to be carefull to don't change any return type. Therefore it will take some time.

**Comment by MartinKuschnik** [comment]
@danielo-unity3d Please give [Version 6.0.0](https://github.com/MartinKuschnik/WmiLight/releases/tag/v6.0.0) a try. This version should work in all deployment cases.
