### ISSUE TITLE
Event watcher question

### ISSUE THREAD

**Issue by Martin12350** [MartinKuschnik/WmiLight#16]
Based on the readme, this library has only one purpose, and that is sending WMI queries.
However, I have to ask: Are You planning to implement [ManagementEventWatcher](https://learn.microsoft.com/en-us/dotnet/api/system.management.managementeventwatcher) or something similar?

Example
```
var watcher = new ManagementEventWatcher(new WqlEventQuery("query"));
watcher.EventArrived += new EventArrivedEventHandler(OnWatcherEvent);
watcher.Start();
```
And if You are curious, why not use the already mentioned Watcher, unfortunately it does not support NativeAOT (yet), so I was searching for some alternatives and found out your library, which works with AOT like a charm.

Or just if You have some suggestions, how to implement something, which would trigger event, I would be glad.

**Comment by MartinKuschnik** [comment]
Hi @Martin12350,

i will have a look to mechanism behind `ManagementEventWatcher`. I think it should be possible to implement it, but it will take a couple days.

**Comment by Martin12350** [comment]
I did not even expect this to be added on my demand, so as much time as You need :)
I was trying to check how they are doing it with [source.dot.net](https://source.dot.net/#System.Management/artifacts/obj/System.Management/Debug/net9.0/System.Management.notsupported.cs,da27703e520f1c80), but only found out `PlatformNotSupportedException`, so I have no idea how it works in my code hehe.

**Comment by MartinKuschnik** [comment]
@Martin12350 I think i have found an implementation that works. The usage will look like:

```c#
using (WmiConnection conncetion = new WmiConnection(/*@"\\MACHINENAME\root\cimv2", cred, opt*/))
{
    using (WmiEventWatcher eventWatcher = conncetion.CreateEventWatcher("SELECT * FROM __InstanceCreationEvent WITHIN 2 WHERE TargetInstance ISA 'Win32_Process'"))
    {
        eventWatcher.EventArrived += EventWatcher_EventArrived;

        eventWatcher.Start();

       /// do your stuff here ....

        eventWatcher.Stop();

        eventWatcher.EventArrived -= EventWatcher_EventArrived;
    }
}
```

It will take some more days to finish the implementation. I need to double check for mem leakes because of the bidirectional reference (unmanaged <-> managed).

**Comment by Martin12350** [comment]
Wow, if it works with NativeAOT, it will be golden!

**Comment by MartinKuschnik** [comment]
Version 6.1.0 should be available at NuGet soon. Please habe a look to this version and give me some feedback.

I also added another way to subscribe to an event:

```C#
var opt = new WmiConnectionOptions() { EnablePackageEncryption = true };

using (WmiConnection con = new WmiConnection(@"\\MACHINENAME\root\cimv2", opt))
{
    using (WmiEventSubscription sub = conncetion.CreateEventSubscription(
            "SELECT * FROM __InstanceCreationEvent WITHIN 2 WHERE TargetInstance ISA 'Win32_Process'", 
            x => Console.WriteLine("Process '{0}' started", x.GetPropertyValue<WmiObject>("TargetInstance").GetPropertyValue<string>("Name"))))
    {
        // ToDo: wait or do some other suff
    }
}
```

**Comment by Martin12350** [comment]
Definitely will try and let you know. Probably tomorrow I will test it in my case scenario :)
Thanks a lot for the fast delivery.

**Comment by Martin12350** [comment]
At first glance, everything works as expected, even with AOT.
However, found out some edge case exception.
I am using those two queries:
> "SELECT * FROM __InstanceCreationEvent WITHIN 2 WHERE TargetInstance ISA 'Win32_PnPEntity'"
> "SELECT * FROM __InstanceDeletionEvent WITHIN 2 WHERE TargetInstance ISA 'Win32_PnPEntity'"

And when I take out and insert some USB quickly, then this exception is thrown:
```
Fatal error. Internal CLR error. (0x80131506)
Repeat 2 times:
--------------------------------
   at WmiLight.NativeMethods.ReleaseIUnknown(IntPtr)
--------------------------------
   at WmiLight.Wbem.IUnknown.Finalize()

An unhandled exception of type 'System.AccessViolationException' occurred in WmiLight.dll.
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Embedded document WmiLight.Wbem\IUnknown.cs was extracted to ..\AppData\Local\Temp\.vsdbgsrc\d3c8a31c2ab8fe917b1a3b712fa30d663c0b5067631a75cc9553238b48be0bea\IUnknown.cs
```

![image](https://github.com/MartinKuschnik/WmiLight/assets/47942899/7c56696a-0eeb-4a82-8762-12e6dc2a1f20)

It is not normal usage to un/plug USB like crazy, but some other queries could have similar issue (maybe?).
Also, noticed that its happening only with NativeAOT (well kind of obvious, when it is coming from NativeMethods).

**Comment by MartinKuschnik** [comment]
@Martin12350 Version 6.1.1 should be accessable in a few minutes and fixes hopfully your issue.

If not i need more details about the way your using the WmiEventSubscription or WmiEventWatcher.

**Comment by MartinKuschnik** [comment]
Validation takes longer than usual:

![image](https://github.com/MartinKuschnik/WmiLight/assets/2582960/c3691eba-2f01-4ea9-9a71-b58269ba1ebd)

**Comment by Martin12350** [comment]
No issue, tomorrow is also day :D
About the setup, I was able to reproduce even with new console app project and enabled NativeAOT to eliminate my code from it.
But it is not consistent, sometimes it happens after one event almost immediately, other time it happens after few mins.
Could not figure out, what is the condition, that triggers it.

**Comment by MartinKuschnik** [comment]
try to force the GC. This thriggered the issue in my case.

**Comment by Martin12350** [comment]
You are right, triggering GC immediately throws.

**Comment by MartinKuschnik** [comment]
Version 6.1.1. is available now.

**Comment by Martin12350** [comment]
Updated, tested and have to say, works without any issue now :)
Will test is more deeply, but looks awesome.
**Thanks a lot** for your time and effort.
Closing this as finished with big success.
Fun final note - in readme, you have typo 'conncetion' :D
