### ISSUE TITLE
Lacking support for Delete instance

### ISSUE THREAD

**Issue by JMyklebust** [MartinKuschnik/WmiLight#27]
Hello, I was trying to migrate a project over from using MMI to using WmiLight for a library more suited for AOT compiling. However i stumbled into a problem that this library does not support deleting instances.

More specifically I'm trying to handle printers, and I'm stuck on the removal part.
This is a snippet of what I'm currently doing (I'm cutting a lot here so the setup might look a bit weird).

````C#
using Microsoft.Management.Infrastructure; //using 3.0.0 here

internal class CIMUtils
{
        const string cimNamespace = @"root\cimv2";
        private static readonly CimSession cimSession = CimSession.Create(null);
        internal static void RemovePrinter(string printerName)
        {
            var printer = cimSession.QueryInstances(cimNamespace, "WQL", $"Select * From Win32_Printer Where name LIKE \"{printerName.Replace(@"\", @"\\")}\"").First();
            cimSession.DeleteInstance(printer);
        }
}
````

This is kind of how i'd expect the syntax could work based on the examples for use of other methods in this library.
````C#
using WmiLight;

internal class CIMUtils
{
        private static readonly WmiConnection wmiConnection = new WmiConnection();
        internal static void RemovePrinter(string printerName)
        {
            foreach (WmiObject printer in wmiConnection.CreateQuery($"Select * From Win32_Printer Where name LIKE \"{printerName.Replace(@"\", @"\\")}\""))
            {
                wmiConnection.DeleteInstance(printer);
            }
        }
}
````

**Comment by MartinKuschnik** [comment]
Hi @JMyklebust,

the Implementation for DeleteInstance should be pretty straight forward.
Give me a few days.

**Comment by MartinKuschnik** [comment]
@JMyklebust Please try version 6.5.0 that should be available in a few minutes.

Please leave some feedback.

**Comment by JMyklebust** [comment]
I've tested this now and it works perfectly.
Thank you, and thanks for the excellent project! :)
