### ISSUE TITLE
X86 AOT Support

### ISSUE THREAD

**Issue by MakesYT** [MartinKuschnik/WmiLight#34]
Net9 introduced AOT x86 suport, but wmilight does not support x86

**Comment by MartinKuschnik** [comment]
Works for me.

![image](https://github.com/user-attachments/assets/961843f3-3425-482a-941a-729a3faa7ae5)

**Comment by MakesYT** [comment]
![image](https://github.com/user-attachments/assets/b4bd5002-80f3-421e-87c6-193b79498cea)
This problem only exists in x86 .
![image](https://github.com/user-attachments/assets/45e20cba-86e5-4dd5-bdcb-e0f13c05f9f7)

**Comment by MartinKuschnik** [comment]
Sorry, I need more information to help you.

Whats the first screenshot?

Can you provide a demo project with the issue?

**Comment by MakesYT** [comment]
https://github.com/MakesYT/FLYSHOW_ToolBox
![image](https://github.com/user-attachments/assets/228bde2f-e1aa-424c-8601-ddb9589839e4)
I am new to this and cannot determine the exact cause of the problem.

**Comment by MartinKuschnik** [comment]
The issue is fixed with version 6.6.0.
