### ISSUE TITLE
Support for NativeAOT in ARM64 compilation

### ISSUE THREAD

**Issue by Sathiyaraman-M** [MartinKuschnik/WmiLight#36]
Hi @MartinKuschnik! Firstly, thanks for building this fantastic library! Because of your library, I am able to successfully replace `System.Management` in my project and build a native win-x64 executable. But when I tried to cross-compile for win-arm64, the compilation failed with a following error.

```
LINK : fatal error LNK1181: cannot open input file 'D:\Cache\NuGet\GlobalPackages\wmilight\6.6.0\build\..\lib\native\win-arm64\WmiLight.Native.lib' 
D:\Cache\NuGet\GlobalPackages\microsoft.dotnet.ilcompiler\8.0.10\build\Microsoft.NETCore.Native.targets(370,5): error MSB3073: The command ""C:\Program Files\Microsoft Visual Studio\2022
\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\arm64\link.exe" @"obj\Release\net8.0\win-arm64\native\link.rsp"" exited with code 1181.
```

As far as I understand, the `WmiLight.Native.vcxproj` didn't target ARM64 and hence it fails to compile for ARM64.

**Comment by MartinKuschnik** [comment]
Hi @Sathiyaraman-M, i did not implemented ARM64 because i do not have a ARM based hardware to test it.

If you have a ARM based hardware to test it, we can achive ARM support.

**Comment by Sathiyaraman-M** [comment]
> If you have a ARM based hardware to test it, we can achive ARM support.

Sadly I don't have any ARM64 hardware that runs windows. I was just simply testing cross-compilation for other architectures from my Windows x64 PC. Found out that win-x86 doesn't support Native AOT but win-arm64 was failing just because the library didn't target ARM64.

I guess we can still test it by checking if it actually cross-compiles to ARM64 properly. Successful cross-compilation itself can be considered a decent level of success.

**Comment by MartinKuschnik** [comment]
I made the nessesary changes.

![image](https://github.com/user-attachments/assets/3cb49a78-b7f8-4d14-a1dd-89ffe476fb8e)
![image](https://github.com/user-attachments/assets/2aaa1726-bb01-4e14-9f43-f2b0397d4fbc)

GitHub does not provide free windows on arm machines for actions. Therfore i can not run unit tests fon arm.
I tested the lib on an azure mechine and it looks good form me.

![image](https://github.com/user-attachments/assets/4e1e7245-a01a-464e-a931-7d8408c41cca)

Please give Version [6.7.0-pre2](https://github.com/MartinKuschnik/WmiLight/releases/tag/v6.7.0-pre2) (pre release) a try. I will make a finel release if this version works for you.

**Comment by Sathiyaraman-M** [comment]
Cool! The cross-compilation is working with the new version. I am able to successfully build a native ARM64 executable now.
