### ISSUE TITLE
GetDeviceProperties need SetPropertyValue method has an array overload

### ISSUE THREAD

**Issue by RERASER** [MartinKuschnik/WmiLight#38]
Microsoft document of GetDeviceProperties:https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/getdeviceproperties-win32-pnpentity

**Comment by MartinKuschnik** [comment]
@RERASER Please try Version 6.8.0 and leave some feedback.

**Comment by RERASER** [comment]
Thank you for your work. It works very well, I can achieve the same result with 8 lines of C# instead of 53 lines of C++ now.
