### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by haseakash** [MartinKuschnik/WmiLight#43]
Im Using Latest WmiLight nuget  6.9.0 .

i converted following code into WmiLight

```
using System.Management;

public class BrightnessControlWMI
{
    public static void SetScreenBrightness(uint brightnessLevel)
    {
        // Ensure brightness level is within valid range
        brightnessLevel = Math.Max(0, Math.Min(100, brightnessLevel));

        // Query for WmiMonitorBrightnessMethods class
        string query = "SELECT * FROM WmiMonitorBrightnessMethods";
        ManagementObjectSearcher searcher = new ManagementObjectSearcher(@"root\wmi", query);
        ManagementObjectCollection queryCollection = searcher.Get();

        foreach (ManagementObject obj in queryCollection)
        {
            // Set brightness using WmiSetBrightness method
            var inParams = obj.GetMethodParameters("WmiSetBrightness");
            inParams["Brightness"] = brightnessLevel;
            inParams["Timeout"] = 0; // No timeout for the change

            obj.InvokeMethod("WmiSetBrightness", inParams, null);
        }
    }
}
```

Here is My WmiLight Code
i removed System.Managemnet nuget

```
using WmiLight;

public class BrightnessControlWmiLight
{

    public static void SetScreenBrightness(uint brightnessLevel)
    {
        using (WmiConnection connection = new WmiConnection(@"\\.\root\wmi"))
        {
            // Query the WmiMonitorBrightnessMethods class to get access to the method
            foreach (var obj in connection.CreateQuery("SELECT * FROM WmiMonitorBrightnessMethods"))
            {
                using (WmiMethod setBrightnessMethod = obj.GetMethod("WmiSetBrightness"))
                using (WmiMethodParameters parameters = setBrightnessMethod.CreateInParameters())
                {
                    parameters.SetPropertyValue("Timeout", "0"); // Timeout in seconds (0 = immediate)
                    parameters.SetPropertyValue("Brightness", brightnessLevel.ToString());

                    uint result = obj.ExecuteMethod<uint>(setBrightnessMethod, parameters, out _);

                    if (result != 0)
                        throw new Exception($"Failed to set brightness. Error code: {result}");
                }
            }
        }
    }
}
```

Now i Call it From My main Form as

```
        private void Button1_Click(object sender, EventArgs e)
        {
            try
            {
                BrightnessControlWmiLight.SetScreenBrightness(100);
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error: " + ex.Message);
            }
}
```

It Chnage the Screen brightness to 100% .
But there are multiple catch ex . ther are not working .

Beacuse problem is it still throwing following error.
 System.NullReferenceException: 'Object reference not set to an instance of an object.' . 

and i checked the problem is in following call .                           ```
// Set the Brightness and Timeout values with additional null checks
                        methodParams?.SetPropertyValue("Brightness", value); // Correct type as uint
                        methodParams?.SetPropertyValue("Timeout", 0); // No timeout for the change

                        // Execute the method and capture the result, using safe invocation
                        uint result = 0;
                        try
                        {
                            result = con.ExecuteMethod<uint>(createMethod, methodParams, out WmiMethodParameters outParameters);
                        }
                        catch (Exception ex)
                        {
                            MessageBox.Show($"Exception during method execution: {ex.Message}");
                        }

```


If not, can you please tell me how to convert my original WMI code in WmiLight ?

**Comment by MartinKuschnik** [comment]
Hi @haseakash,

I’m not entirely sure, but it seems that the method `WmiSetBrightness` doesn’t return a value, similar to other WMI methods. I’ll work on creating a new version that addresses this edge case.

**Comment by MartinKuschnik** [comment]
Please give version [6.9.1](https://www.nuget.org/packages/WmiLight/6.9.1) a try.  Your code already looks pretty good.

Feedback would be nice.
