### ISSUE TITLE
UseIntegratedWindowsAuthentication for remote connections

### ISSUE THREAD

**Issue by chrismdev** [MartinKuschnik/WmiLight#5]
Hi,

When connecting to remote computers using windows auth in a domain, wmilight doesn't seem to handle that scenario unless I missed somethings.
I added:

`public bool UseIntegratedWindowsAuthentication { get; set; } `

to WmiConnectionOptions, then added:

```
    if (this.options.UseIntegratedWindowsAuthentication)
    {
        this.ignoreCredential = true;
        this.wbemServices = locator.ConnectServer(this.path, null, null, null, WbemConnectOption.None, null, this.context);
        this.wbemServices.SetProxy(ImpersonationLevel.Impersonate, authLevel);
    }
```
to WmiConnection but there must be a better way of doing this.

**Comment by MartinKuschnik** [comment]
Is it working with the changes you made?

**Comment by MartinKuschnik** [comment]
I dived a bit deeper into it.

Auth with the integrated user is pretty simple.
Just create a connection without credentials:

```C#

var opt = new WmiConnectionOptions() { EnablePackageEncryption = true };

using (WmiConnection con = new WmiConnection(@"\\MACHINENAME\root\cimv2", opt))
{
    foreach (WmiObject partition in con.CreateQuery("SELECT * FROM Win32_DiskPartition"))
    {
        Console.WriteLine(partition["Name"]);
    }
}
```
Does this help you?

**Comment by chrismdev** [comment]
I thought it would be simple. Thank you
