### ISSUE TITLE
More permissive license?

### ISSUE THREAD

**Issue by natan-abolafya** [MartinKuschnik/WmiLight#7]
Hey.

Came across your library on this [discussion ](https://github.com/dotnet/runtime/issues/61960#issuecomment-1354299822) and decided to give it a try and it worked quite nicely. Only noticed at the last second that it's GPL licensed. Any chance you could use a more permissive license like MIT or Apache 2.0?

**Comment by MartinKuschnik** [comment]
Hey,

ich have changed the license to MIT. Have fun with it.

What kind of project do you are using WmiLight?

**Comment by natan-abolafya** [comment]
Fantastic! Thank you.

It's an enterprise level desktop application where we gather a couple of information about Windows such as Windows version and device Id. We don't depend on WMI that much but we need that information in the way WMI reports. 
Our goal wasn't to fix the memory leak you mentioned in the readme, but rather move away from COM.

**Comment by natan-abolafya** [comment]
Apparently, I have tested this wrong before. WmiLight seems to be using COM also as the calls seem to be failing with
```
WMI failed while retrieving device ID. Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.
```
now.

**Comment by MartinKuschnik** [comment]
WmiLight uses also COM :-(

**Comment by natan-abolafya** [comment]
It's possible that [this comment](https://github.com/dotnet/runtime/issues/61960#issuecomment-1354299822) meant that trimming works better even when COM is enabled on the project. I will try that next.

**Comment by MartinKuschnik** [comment]
Ok, meaning you would like to shink the size of your application by using the trimmingfunction during build?

**Comment by MartinKuschnik** [comment]
Partial trim woks if this is an option.

```
<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
<TrimMode>partial</TrimMode>
```

**Comment by natan-abolafya** [comment]
On .NET 6, I was already using `<TrimMode>CopyUsed</TrimMode>` with System.Management library and it was working. But I wanted to use the `Link` mode, which I'm guessing means `Full` on .NET 7; and that was crashing.

I've enabled COM with WmiLight now and the full trim mode, it's working better than System.Management which is great. So I guess that's what the commenter meant.

**Comment by MartinKuschnik** [comment]
Ok, very nice.

Have fun!
